#Correlations between Gs and VPD under the different SWC levels
library(RColorBrewer)
library(readr)
library(DescTools)
library(pgirmess)
library(Hmisc)
library(RColorBrewer)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(plotluck)
library(psych)
library(ggthemes)
library(tidyverse)
library(Rmisc)
library(readr)
library(ggsci)
library(gridExtra)
library(ggpubr)
library(ggpmisc)
hztemp <- read.csv("E:\\RP\\carbon fluex\\Carbonfluxes_GS and GPP20210609.csv")
glimpse(hztemp , width = 40)
p <- ggplot(hztemp, aes(x = VPD_F, y = Gs_mol)) + geom_point(aes(color=SWC_CL),alpha = 0.65) + geom_smooth(aes(color =SWC_CL), method = 'lm', se = TRUE, show.legend = FALSE) + theme_bw() + theme(axis.title.x =element_text(size=17), axis.title.y=element_text(size=17),axis.text=element_text(size=14,family ="Times", face = "plain"))
p
p + scale_color_manual(values = c("#FF6600","#FFCC66","#33FF00","#FFFF33","#FF0033","#0000FF","#00CCFF"))
ggsave("Correlations between Gs and VPD under the different SWC levels.tiff",width=180, height=160, units="mm", dpi=800) 
